apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
data:
  primary.cnf: |
    # Apply this config only on the primary.
    [mysqld]
    log-bin
    test
  replica.cnf: |
    # Apply this config only on replicas.
    [mysqld]
    super-read-only
